// packages/support/resources/js/react/Breadcrumbs.tsx
import {
    createElement,
    forwardRef,
    type ComponentPropsWithoutRef,
    type ReactNode,
} from 'react'
import {
    breadcrumbSeparator,
    breadcrumbSeparatorRtl,
} from '../components/breadcrumbs'

export type BreadcrumbItem = Omit<
    ComponentPropsWithoutRef<'a'>,
    'children' | 'dangerouslySetInnerHTML'
> & { label: string; [attribute: `data-${string}`]: unknown }

export type BreadcrumbsProps = Omit<
    ComponentPropsWithoutRef<'nav'>,
    'children' | 'dangerouslySetInnerHTML'
> & {
    breadcrumbs?: readonly BreadcrumbItem[]
    separator?: ReactNode
    separatorRtl?: ReactNode
}

export default forwardRef<HTMLElement, BreadcrumbsProps>(function Breadcrumbs(
    {
        breadcrumbs = [],
        separator,
        separatorRtl,
        className,
        'aria-label': ariaLabel = 'Breadcrumbs',
        ...attributes
    },
    ref,
) {
    return createElement(
        'nav',
        {
            ...attributes,
            ref,
            'aria-label': ariaLabel,
            className: ['fi-breadcrumbs', className].filter(Boolean).join(' '),
        },
        createElement(
            'ol',
            { className: 'fi-breadcrumbs-list' },
            breadcrumbs.map(({ label, className, ...attributes }, index) =>
                createElement(
                    'li',
                    { className: 'fi-breadcrumbs-item', key: index },
                    index > 0 &&
                        (
                            [
                                ['ltr', separator, breadcrumbSeparator],
                                ['rtl', separatorRtl, breadcrumbSeparatorRtl],
                            ] as const
                        ).map(([direction, content, path]) =>
                            content !== undefined
                                ? createElement(
                                      'span',
                                      {
                                          key: direction,
                                          'aria-hidden': true,
                                          className: `fi-icon fi-size-md fi-breadcrumbs-item-separator fi-${direction}`,
                                      },
                                      content,
                                  )
                                : createElement(
                                      'svg',
                                      {
                                          key: direction,
                                          xmlns: 'http://www.w3.org/2000/svg',
                                          viewBox: '0 0 20 20',
                                          fill: 'currentColor',
                                          'aria-hidden': true,
                                          'data-slot': 'icon',
                                          className: `fi-icon fi-size-md fi-breadcrumbs-item-separator fi-${direction}`,
                                      },
                                      createElement('path', {
                                          fillRule: 'evenodd',
                                          d: path,
                                          clipRule: 'evenodd',
                                      }),
                                  ),
                        ),
                    createElement(
                        attributes.href === undefined ? 'span' : 'a',
                        {
                            ...attributes,
                            'aria-current':
                                index === breadcrumbs.length - 1
                                    ? 'page'
                                    : undefined,
                            className: ['fi-breadcrumbs-item-label', className]
                                .filter(Boolean)
                                .join(' '),
                        },
                        label,
                    ),
                ),
            ),
        ),
    )
})

// packages/support/resources/js/vue/Breadcrumbs.vue
<script setup lang="ts">
import { computed, type AnchorHTMLAttributes, type HTMLAttributes } from 'vue'
import {
    breadcrumbSeparator,
    breadcrumbSeparatorRtl,
} from '../components/breadcrumbs'

type BreadcrumbItem = Omit<
    AnchorHTMLAttributes,
    'innerHTML' | 'textContent'
> & { label: string; [attribute: `data-${string}`]: unknown }

interface BreadcrumbsProps extends /* @vue-ignore */ HTMLAttributes {
    breadcrumbs?: readonly BreadcrumbItem[]
}

const props = withDefaults(defineProps<BreadcrumbsProps>(), {
    breadcrumbs: () => [],
})
const items = computed(() =>
    props.breadcrumbs.map(({ label, class: className, ...attributes }) => ({
        label,
        className,
        attributes,
    })),
)
</script>

<template>
    <nav aria-label="Breadcrumbs" class="fi-breadcrumbs">
        <ol class="fi-breadcrumbs-list">
            <li
                v-for="(item, index) in items"
                :key="index"
                class="fi-breadcrumbs-item"
            >
                <template v-if="index > 0">
                    <span
                        v-if="$slots.separator"
                        aria-hidden="true"
                        class="fi-icon fi-size-md fi-breadcrumbs-item-separator fi-ltr"
                        ><slot name="separator"
                    /></span>
                    <svg
                        v-else
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                        aria-hidden="true"
                        v-bind="{ 'data-slot': 'icon' }"
                        class="fi-icon fi-size-md fi-breadcrumbs-item-separator fi-ltr"
                    >
                        <path
                            fill-rule="evenodd"
                            :d="breadcrumbSeparator"
                            clip-rule="evenodd"
                        />
                    </svg>
                    <span
                        v-if="$slots.separatorRtl"
                        aria-hidden="true"
                        class="fi-icon fi-size-md fi-breadcrumbs-item-separator fi-rtl"
                        ><slot name="separatorRtl"
                    /></span>
                    <svg
                        v-else
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                        aria-hidden="true"
                        v-bind="{ 'data-slot': 'icon' }"
                        class="fi-icon fi-size-md fi-breadcrumbs-item-separator fi-rtl"
                    >
                        <path
                            fill-rule="evenodd"
                            :d="breadcrumbSeparatorRtl"
                            clip-rule="evenodd"
                        />
                    </svg>
                </template>
                <component
                    :is="item.attributes.href === undefined ? 'span' : 'a'"
                    v-bind="item.attributes"
                    :aria-current="
                        index === items.length - 1 ? 'page' : undefined
                    "
                    :class="['fi-breadcrumbs-item-label', item.className]"
                    >{{ item.label }}</component
                >
            </li>
        </ol>
    </nav>
</template>
