// packages/support/resources/js/react/EmptyState.tsx
import {
    createElement,
    forwardRef,
    type ComponentPropsWithoutRef,
    type ReactNode,
} from 'react'
import Icon from './Icon'
import type { IconSize } from '../components/icon'

export type EmptyStateProps = Omit<
    ComponentPropsWithoutRef<'div'>,
    'dangerouslySetInnerHTML'
> & {
    compact?: boolean
    contained?: boolean
    heading?: ReactNode
    headingTag?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
    description?: ReactNode
    footer?: ReactNode
    icon?: ReactNode
    iconColor?: string
    iconSize?: IconSize
}

export default forwardRef<HTMLDivElement, EmptyStateProps>(function EmptyState(
    {
        compact = false,
        contained = true,
        heading,
        headingTag = 'h2',
        description,
        footer,
        children,
        icon,
        iconColor = 'primary',
        iconSize = 'lg',
        className,
        ...attributes
    },
    ref,
) {
    const hasContent = (content: ReactNode): boolean =>
        content != null &&
        typeof content !== 'boolean' &&
        (typeof content !== 'string' || content.trim() !== '')
    const color = iconColor === 'gray' ? '' : `fi-color fi-color-${iconColor}`
    const actions = footer ?? children

    return createElement(
        'div',
        {
            ...attributes,
            ref,
            className: [
                'fi-empty-state',
                compact && 'fi-compact',
                !contained && 'fi-empty-state-not-contained',
                className,
            ]
                .filter(Boolean)
                .join(' '),
        },
        createElement(
            'div',
            { className: 'fi-empty-state-content' },
            hasContent(icon)
                ? createElement(
                      'div',
                      {
                          className: ['fi-empty-state-icon-bg', color]
                              .filter(Boolean)
                              .join(' '),
                      },
                      createElement(
                          Icon,
                          { size: iconSize, className: color || undefined },
                          icon,
                      ),
                  )
                : null,
            createElement(
                'div',
                { className: 'fi-empty-state-text-ctn' },
                createElement(
                    headingTag,
                    { className: 'fi-empty-state-heading' },
                    heading,
                ),
                hasContent(description)
                    ? createElement(
                          'p',
                          { className: 'fi-empty-state-description' },
                          description,
                      )
                    : null,
                hasContent(actions)
                    ? createElement(
                          'footer',
                          { className: 'fi-empty-state-footer' },
                          actions,
                      )
                    : null,
            ),
        ),
    )
})

// packages/support/resources/js/vue/EmptyState.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import Icon from './Icon.vue'
import type { IconSize } from '../components/icon'

interface EmptyStateProps extends /* @vue-ignore */ Omit<
    HTMLAttributes,
    'innerHTML' | 'textContent'
> {
    compact?: boolean
    contained?: boolean
    heading?: string | null
    headingTag?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
    description?: string | null
    footer?: string | null
    iconColor?: string
    iconSize?: IconSize
}
withDefaults(defineProps<EmptyStateProps>(), {
    compact: false,
    contained: true,
    headingTag: 'h2',
    iconColor: 'primary',
    iconSize: 'lg',
})
defineSlots<{
    default?(): unknown
    heading?(): unknown
    description?(): unknown
    footer?(): unknown
    icon?(): unknown
}>()
</script>

<template>
    <div
        :class="[
            'fi-empty-state',
            {
                'fi-compact': compact,
                'fi-empty-state-not-contained': !contained,
            },
        ]"
    >
        <div class="fi-empty-state-content">
            <div
                v-if="$slots.icon"
                :class="[
                    'fi-empty-state-icon-bg',
                    iconColor !== 'gray' && `fi-color fi-color-${iconColor}`,
                ]"
            >
                <Icon
                    :size="iconSize"
                    :class="
                        iconColor !== 'gray'
                            ? `fi-color fi-color-${iconColor}`
                            : undefined
                    "
                    ><slot name="icon"
                /></Icon>
            </div>
            <div class="fi-empty-state-text-ctn">
                <component :is="headingTag" class="fi-empty-state-heading"
                    ><slot name="heading">{{ heading }}</slot></component
                >
                <p
                    v-if="$slots.description || description?.trim()"
                    class="fi-empty-state-description"
                >
                    <slot name="description">{{ description }}</slot>
                </p>
                <footer
                    v-if="$slots.footer || $slots.default || footer?.trim()"
                    class="fi-empty-state-footer"
                >
                    <slot name="footer"
                        ><slot>{{ footer }}</slot></slot
                    >
                </footer>
            </div>
        </div>
    </div>
</template>
