// packages/support/resources/js/react/LoadingSection.tsx
import { createElement, forwardRef, type ComponentPropsWithoutRef } from 'react'
import {
    getLoadingSectionLayout,
    type LoadingSectionOptions,
} from '../components/loading-section'

export type LoadingSectionProps = Omit<
    ComponentPropsWithoutRef<'div'>,
    'children' | 'dangerouslySetInnerHTML'
> &
    LoadingSectionOptions

export default forwardRef<HTMLDivElement, LoadingSectionProps>(
    function LoadingSection(
        {
            columnSpan,
            columnStart,
            height,
            loadingLabel,
            className,
            style,
            ...attributes
        },
        ref,
    ) {
        const layout = getLoadingSectionLayout({
            columnSpan,
            columnStart,
            height,
        })
        return createElement(
            'div',
            {
                role: 'status',
                'aria-busy': true,
                ...attributes,
                ref,
                className: [layout.className, className]
                    .filter(Boolean)
                    .join(' '),
                style: { ...layout.style, ...style },
            },
            createElement(
                'span',
                { className: 'fi-sr-only' },
                loadingLabel ?? 'Loading...',
            ),
        )
    },
)

// packages/support/resources/js/vue/LoadingSection.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { getLoadingSectionLayout } from '../components/loading-section'

interface LoadingSectionProps extends /* @vue-ignore */ Omit<
    HTMLAttributes,
    'innerHTML' | 'textContent'
> {
    columnSpan?: number | string | null | Record<string, number | string | null>
    columnStart?:
        | number
        | `${number}`
        | null
        | Record<string, number | `${number}` | null>
    height?: string | null
    loadingLabel?: string | null
}
defineProps<LoadingSectionProps>()
</script>

<template>
    <div
        role="status"
        aria-busy="true"
        :class="
            getLoadingSectionLayout({ columnSpan, columnStart, height })
                .className
        "
        :style="
            getLoadingSectionLayout({ columnSpan, columnStart, height }).style
        "
    >
        <span class="fi-sr-only">{{ loadingLabel ?? 'Loading...' }}</span>
    </div>
</template>
