// packages/support/resources/js/vue/Badge.vue
<script setup lang="ts">
import {
    computed,
    ref,
    watchEffect,
    type AnchorHTMLAttributes,
    type ButtonHTMLAttributes,
} from 'vue'
import { getBadgeClasses } from '../components/badge'
import type { IconSize } from '../components/icon'
import { interactive } from '../components/interactive'
import Icon from './Icon.vue'
import LoadingIndicator from './LoadingIndicator.vue'
defineOptions({ inheritAttrs: false })
interface BadgeProps extends /* @vue-ignore */ Omit<
    AnchorHTMLAttributes & ButtonHTMLAttributes,
    'color' | 'disabled' | 'innerHTML' | 'textContent'
> {
    tag?: 'span' | 'a' | 'button'
    color?: string
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
    iconPosition?: 'before' | 'after'
    iconSize?: IconSize
    loading?: boolean
    disabled?: boolean
    tooltip?: string | null
    keyBindings?: string[]
    deleteLabel?: string
    deleteLoading?: boolean
    onDelete?: (event: MouseEvent) => void
}
const props = withDefaults(defineProps<BadgeProps>(), {
    tag: 'span',
    color: 'primary',
    size: 'md',
    iconPosition: 'before',
    iconSize: 'sm',
    deleteLabel: 'Delete',
})
const element = ref<HTMLElement>()
const keyBindingsSignature = computed(() =>
    JSON.stringify(props.keyBindings ?? []),
)
defineExpose({ element })
defineSlots<{ default?(): unknown; icon?(): unknown }>()
watchEffect((cleanup) => {
    if (props.onDelete && props.tag !== 'span')
        throw new Error('Deletable badges must use tag="span".')
    if (element.value)
        cleanup(
            interactive(element.value, {
                tooltip: props.tooltip,
                keyBindings: JSON.parse(keyBindingsSignature.value),
                disabled: props.disabled || props.loading,
            }),
        )
})
function click(event: MouseEvent) {
    if (props.disabled || props.loading) {
        event.preventDefault()
        event.stopImmediatePropagation()
    }
}
</script>
<template>
    <component
        :is="tag"
        ref="element"
        v-bind="$attrs"
        :class="getBadgeClasses(props)"
        :href="tag === 'a' && !(disabled || loading) ? $attrs.href : undefined"
        :role="
            $attrs.role ??
            (tag === 'a' && $attrs.href != null && (disabled || loading)
                ? 'link'
                : undefined)
        "
        :type="tag === 'button' ? ($attrs.type ?? 'button') : undefined"
        :disabled="
            tag === 'button' && (disabled || loading) && !tooltip
                ? true
                : undefined
        "
        :aria-disabled="disabled || loading || undefined"
        :aria-busy="loading || undefined"
        :tabindex="
            (disabled || loading) && tooltip
                ? ($attrs.tabindex ?? 0)
                : $attrs.tabindex
        "
        :style="
            (disabled || loading) && tooltip
                ? { pointerEvents: 'auto' }
                : undefined
        "
        @click.capture="click"
    >
        <template v-if="iconPosition === 'before'">
            <LoadingIndicator v-if="loading" :size="iconSize" />
            <Icon v-else-if="$slots.icon" :size="iconSize" aria-hidden="true"
                ><slot name="icon"
            /></Icon>
        </template>
        <span class="fi-badge-label-ctn"
            ><span class="fi-badge-label"><slot /></span
        ></span>
        <button
            v-if="onDelete"
            type="button"
            class="fi-badge-delete-btn"
            :disabled="disabled || loading || deleteLoading"
            :aria-busy="deleteLoading || undefined"
            @click.stop="
                (event) => {
                    if (!(disabled || loading || deleteLoading))
                        onDelete?.(event)
                }
            "
        >
            <LoadingIndicator v-if="deleteLoading" size="xs" />
            <span v-else class="fi-badge-delete-btn-icon" aria-hidden="true" />
            <span class="fi-sr-only">{{
                deleteLabel.trim() ? deleteLabel : 'Delete'
            }}</span>
        </button>
        <template v-else-if="iconPosition === 'after'">
            <LoadingIndicator v-if="loading" :size="iconSize" />
            <Icon v-else-if="$slots.icon" :size="iconSize" aria-hidden="true"
                ><slot name="icon"
            /></Icon>
        </template>
    </component>
</template>

// packages/support/resources/js/react/Badge.tsx
import {
    createElement,
    forwardRef,
    useEffect,
    useImperativeHandle,
    useRef,
    type AnchorHTMLAttributes,
    type ButtonHTMLAttributes,
    type ReactNode,
} from 'react'
import { getBadgeClasses, type BadgeOptions } from '../components/badge'
import { interactive } from '../components/interactive'
import Icon from './Icon'
import LoadingIndicator from './LoadingIndicator'

export type BadgeProps = Omit<
    ButtonHTMLAttributes<HTMLElement> & AnchorHTMLAttributes<HTMLElement>,
    'children' | 'dangerouslySetInnerHTML' | 'color'
> &
    Omit<BadgeOptions, 'tag'> & {
        children?: ReactNode
        icon?: ReactNode
    } & (
        | {
              tag?: 'span'
              onDelete?: React.MouseEventHandler<HTMLButtonElement>
          }
        | { tag: 'a' | 'button'; onDelete?: never }
    )

export default forwardRef<HTMLElement, BadgeProps>(function Badge(
    {
        tag = 'span',
        color = 'primary',
        size = 'md',
        icon,
        iconPosition = 'before',
        iconSize = 'sm',
        loading = false,
        disabled = false,
        tooltip,
        keyBindings,
        deleteLabel = 'Delete',
        deleteLoading = false,
        onDelete,
        children,
        className,
        style,
        onClick,
        href,
        type = 'button',
        tabIndex,
        ...attributes
    },
    ref,
) {
    const element = useRef<HTMLElement>(null)
    useImperativeHandle(ref, () => element.current!, [tag])
    const blocked = disabled || loading
    const keyBindingsSignature = JSON.stringify(keyBindings ?? [])
    useEffect(
        () =>
            element.current
                ? interactive(element.current, {
                      tooltip,
                      keyBindings: JSON.parse(keyBindingsSignature),
                      disabled: blocked,
                  })
                : undefined,
        [tooltip, keyBindingsSignature, blocked, tag],
    )
    if (onDelete && tag !== 'span')
        throw new Error('Deletable badges must use tag="span".')
    const indicator = loading
        ? createElement(LoadingIndicator, { size: iconSize })
        : icon != null
          ? createElement(Icon, { size: iconSize, 'aria-hidden': true }, icon)
          : null
    return createElement(
        tag,
        {
            ...attributes,
            ref: element,
            href: tag === 'a' && !blocked ? href : undefined,
            role:
                attributes.role ??
                (tag === 'a' && href != null && blocked ? 'link' : undefined),
            type: tag === 'button' ? type : undefined,
            disabled:
                tag === 'button' && blocked && !tooltip ? true : undefined,
            'aria-disabled': blocked || undefined,
            'aria-busy': loading || undefined,
            tabIndex: blocked && tooltip ? (tabIndex ?? 0) : tabIndex,
            style: {
                ...style,
                ...(blocked && tooltip ? { pointerEvents: 'auto' } : {}),
            },
            className: [
                getBadgeClasses({ color, size, disabled, loading }),
                className,
            ]
                .filter(Boolean)
                .join(' '),
            onClick: (event: React.MouseEvent<HTMLElement>) => {
                if (blocked) {
                    event.preventDefault()
                    event.stopPropagation()
                    return
                }
                onClick?.(event)
            },
        },
        iconPosition === 'before' ? indicator : null,
        createElement(
            'span',
            { className: 'fi-badge-label-ctn' },
            createElement('span', { className: 'fi-badge-label' }, children),
        ),
        onDelete
            ? createElement(
                  'button',
                  {
                      type: 'button',
                      className: 'fi-badge-delete-btn',
                      disabled: blocked || deleteLoading,
                      'aria-busy': deleteLoading || undefined,
                      onClick: (event: React.MouseEvent<HTMLButtonElement>) => {
                          event.stopPropagation()
                          if (!blocked && !deleteLoading) onDelete(event)
                      },
                  },
                  deleteLoading
                      ? createElement(LoadingIndicator, { size: 'xs' })
                      : createElement('span', {
                            className: 'fi-badge-delete-btn-icon',
                            'aria-hidden': true,
                        }),
                  createElement(
                      'span',
                      { className: 'fi-sr-only' },
                      deleteLabel.trim() ? deleteLabel : 'Delete',
                  ),
              )
            : iconPosition === 'after'
              ? indicator
              : null,
    )
})
