// packages/support/resources/js/vue/Callout.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import Icon from './Icon.vue'
import type { IconSize } from '../components/icon'

interface CalloutProps extends /* @vue-ignore */ Omit<
    HTMLAttributes,
    'innerHTML' | 'textContent'
> {
    color?: string
    heading?: string | null
    description?: string | null
    footer?: string | null
    controls?: string | null
    iconColor?: string
    iconSize?: IconSize
}
withDefaults(defineProps<CalloutProps>(), { color: 'gray', iconSize: 'lg' })
defineSlots<{
    default?(): unknown
    heading?(): unknown
    description?(): unknown
    footer?(): unknown
    controls?(): unknown
    icon?(): unknown
}>()
</script>

<template>
    <div
        :class="[
            'fi-callout',
            color !== 'gray' && `fi-color fi-color-${color}`,
        ]"
    >
        <Icon
            v-if="$slots.icon"
            :size="iconSize"
            aria-hidden="true"
            :class="[
                'fi-callout-icon',
                (iconColor ?? color) !== 'gray' &&
                    `fi-color fi-color-${iconColor ?? color}`,
            ]"
            ><slot name="icon"
        /></Icon>
        <div
            v-if="
                $slots.heading ||
                heading?.trim() ||
                $slots.description ||
                description?.trim() ||
                $slots.footer ||
                $slots.default ||
                footer?.trim()
            "
            class="fi-callout-main"
        >
            <div
                v-if="
                    $slots.heading ||
                    heading?.trim() ||
                    $slots.description ||
                    description?.trim()
                "
                class="fi-callout-text"
            >
                <h4
                    v-if="$slots.heading || heading?.trim()"
                    class="fi-callout-heading"
                >
                    <slot name="heading">{{ heading }}</slot>
                </h4>
                <p
                    v-if="$slots.description || description?.trim()"
                    class="fi-callout-description"
                >
                    <slot name="description">{{ description }}</slot>
                </p>
            </div>
            <div
                v-if="$slots.footer || $slots.default || footer?.trim()"
                class="fi-callout-footer"
            >
                <slot name="footer"
                    ><slot>{{ footer }}</slot></slot
                >
            </div>
        </div>
        <div
            v-if="$slots.controls || controls?.trim()"
            class="fi-callout-controls"
        >
            <slot name="controls">{{ controls }}</slot>
        </div>
    </div>
</template>

// packages/support/resources/js/react/Callout.tsx
import {
    createElement,
    forwardRef,
    type ComponentPropsWithoutRef,
    type ReactNode,
} from 'react'
import Icon from './Icon'
import type { IconSize } from '../components/icon'

export type CalloutProps = Omit<
    ComponentPropsWithoutRef<'div'>,
    'dangerouslySetInnerHTML'
> & {
    color?: string
    heading?: ReactNode
    description?: ReactNode
    footer?: ReactNode
    controls?: ReactNode
    icon?: ReactNode
    iconColor?: string
    iconSize?: IconSize
}

export default forwardRef<HTMLDivElement, CalloutProps>(function Callout(
    {
        color = 'gray',
        heading,
        description,
        footer,
        controls,
        children,
        icon,
        iconColor = color,
        iconSize = 'lg',
        className,
        ...attributes
    },
    ref,
) {
    const hasContent = (content: ReactNode): boolean =>
        content != null &&
        typeof content !== 'boolean' &&
        (typeof content !== 'string' || content.trim() !== '')
    const actions = footer ?? children
    const hasText = hasContent(heading) || hasContent(description)
    return createElement(
        'div',
        {
            ...attributes,
            ref,
            className: [
                'fi-callout',
                color !== 'gray' && `fi-color fi-color-${color}`,
                className,
            ]
                .filter(Boolean)
                .join(' '),
        },
        hasContent(icon)
            ? createElement(
                  Icon,
                  {
                      size: iconSize,
                      'aria-hidden': true,
                      className: [
                          'fi-callout-icon',
                          iconColor !== 'gray' &&
                              `fi-color fi-color-${iconColor}`,
                      ]
                          .filter(Boolean)
                          .join(' '),
                  },
                  icon,
              )
            : null,
        hasText || hasContent(actions)
            ? createElement(
                  'div',
                  { className: 'fi-callout-main' },
                  hasText
                      ? createElement(
                            'div',
                            { className: 'fi-callout-text' },
                            hasContent(heading)
                                ? createElement(
                                      'h4',
                                      { className: 'fi-callout-heading' },
                                      heading,
                                  )
                                : null,
                            hasContent(description)
                                ? createElement(
                                      'p',
                                      { className: 'fi-callout-description' },
                                      description,
                                  )
                                : null,
                        )
                      : null,
                  hasContent(actions)
                      ? createElement(
                            'div',
                            { className: 'fi-callout-footer' },
                            actions,
                        )
                      : null,
              )
            : null,
        hasContent(controls)
            ? createElement(
                  'div',
                  { className: 'fi-callout-controls' },
                  controls,
              )
            : null,
    )
})
