// packages/support/resources/js/vue/Fieldset.vue
<script setup lang="ts">
import type { FieldsetHTMLAttributes } from 'vue'

interface FieldsetProps extends /* @vue-ignore */ FieldsetHTMLAttributes {
    contained?: boolean
    label?: string | null
    labelHidden?: boolean
    required?: boolean
}

withDefaults(defineProps<FieldsetProps>(), {
    contained: true,
    label: null,
    labelHidden: false,
    required: false,
})

defineSlots<{
    default?(): unknown
    label?(): unknown
}>()
</script>

<template>
    <fieldset
        :class="[
            'fi-fieldset',
            {
                'fi-fieldset-label-hidden': labelHidden,
                'fi-fieldset-not-contained': !contained,
            },
        ]"
    >
        <legend v-if="$slots.label || label?.trim()">
            <slot name="label">{{ label }}</slot
            ><sup v-if="required" class="fi-fieldset-label-required-mark"
                >*</sup
            >
        </legend>
        <slot />
    </fieldset>
</template>

// packages/support/resources/js/react/Fieldset.tsx
import {
    createElement,
    forwardRef,
    type ComponentPropsWithoutRef,
    type ReactNode,
} from 'react'

export type FieldsetProps = ComponentPropsWithoutRef<'fieldset'> & {
    contained?: boolean
    label?: ReactNode
    labelHidden?: boolean
    required?: boolean
}

export default forwardRef<HTMLFieldSetElement, FieldsetProps>(function Fieldset(
    {
        contained = true,
        label = null,
        labelHidden = false,
        required = false,
        className,
        children,
        ...attributes
    },
    ref,
) {
    return createElement(
        'fieldset',
        {
            ...attributes,
            ref,
            className: [
                'fi-fieldset',
                labelHidden && 'fi-fieldset-label-hidden',
                !contained && 'fi-fieldset-not-contained',
                className,
            ]
                .filter(Boolean)
                .join(' '),
        },
        label != null &&
            typeof label !== 'boolean' &&
            (typeof label !== 'string' || label.trim() !== '')
            ? createElement(
                  'legend',
                  null,
                  label,
                  required
                      ? createElement(
                            'sup',
                            { className: 'fi-fieldset-label-required-mark' },
                            '*',
                        )
                      : null,
              )
            : null,
        children,
    )
})
