// packages/support/resources/js/svelte/Input.svelte
<script lang="ts">
    import type { HTMLInputAttributes } from 'svelte/elements'

    let {
        inlinePrefix = false,
        inlineSuffix = false,
        element = $bindable(),
        value = $bindable(),
        class: className = '',
        ...attributes
    }: Omit<HTMLInputAttributes, 'children' | 'class' | 'value'> & {
        inlinePrefix?: boolean
        inlineSuffix?: boolean
        element?: HTMLInputElement
        value?: string | number
        class?: string
    } = $props()
</script>

<input
    {...attributes}
    bind:this={element}
    bind:value
    class={[
        'fi-input',
        inlinePrefix && 'fi-input-has-inline-prefix',
        inlineSuffix && 'fi-input-has-inline-suffix',
        className,
    ]
        .filter(Boolean)
        .join(' ')}
/>

// packages/support/resources/js/react/Input.tsx
import { createElement, forwardRef, type ComponentPropsWithoutRef } from 'react'

export type InputProps = Omit<
    ComponentPropsWithoutRef<'input'>,
    'children' | 'dangerouslySetInnerHTML'
> & {
    inlinePrefix?: boolean
    inlineSuffix?: boolean
}

export default forwardRef<HTMLInputElement, InputProps>(function Input(
    { inlinePrefix = false, inlineSuffix = false, className, ...attributes },
    ref,
) {
    return createElement('input', {
        ...attributes,
        ref,
        className: [
            'fi-input',
            inlinePrefix && 'fi-input-has-inline-prefix',
            inlineSuffix && 'fi-input-has-inline-suffix',
            className,
        ]
            .filter(Boolean)
            .join(' '),
    })
})
