// packages/support/resources/js/svelte/Radio.svelte
<script lang="ts">
    import type { HTMLInputAttributes } from 'svelte/elements'

    let {
        valid = true,
        group = $bindable(),
        value = 'on',
        class: className = '',
        onchange,
        ...attributes
    }: Omit<HTMLInputAttributes, 'type' | 'class' | 'children' | 'value'> & {
        valid?: boolean
        group?: string | null
        value?: string
        class?: string
    } = $props()
</script>

<input
    {...{
        ...attributes,
        ...(group === undefined
            ? {}
            : { checked: group === value, defaultChecked: group === value }),
    }}
    type="radio"
    {value}
    onchange={(event) => {
        if (group !== undefined) group = event.currentTarget.value
        onchange?.(event)
    }}
    class={['fi-radio-input', !valid && 'fi-invalid', className]
        .filter(Boolean)
        .join(' ')}
/>

// packages/support/resources/js/react/Radio.tsx
import { createElement, forwardRef, type ComponentPropsWithoutRef } from 'react'

export type RadioProps = Omit<
    ComponentPropsWithoutRef<'input'>,
    'type' | 'children' | 'dangerouslySetInnerHTML'
> & {
    valid?: boolean
}

export default forwardRef<HTMLInputElement, RadioProps>(function Radio(
    { valid = true, className, ...attributes },
    ref,
) {
    return createElement('input', {
        ...attributes,
        type: 'radio',
        ref,
        className: ['fi-radio-input', !valid && 'fi-invalid', className]
            .filter(Boolean)
            .join(' '),
    })
})
