// packages/support/resources/js/react/Fieldset.tsx
import {
    createElement,
    forwardRef,
    type ComponentPropsWithoutRef,
    type ReactNode,
} from 'react'

export type FieldsetProps = Omit<
    ComponentPropsWithoutRef<'fieldset'>,
    'dangerouslySetInnerHTML'
> & {
    contained?: boolean
    label?: ReactNode
    labelHidden?: boolean
    required?: boolean
}

export default forwardRef<HTMLFieldSetElement, FieldsetProps>(function Fieldset(
    {
        contained = true,
        label = null,
        labelHidden = false,
        required = false,
        className,
        children,
        ...attributes
    },
    ref,
) {
    return createElement(
        'fieldset',
        {
            ...attributes,
            ref,
            className: [
                'fi-fieldset',
                labelHidden && 'fi-fieldset-label-hidden',
                !contained && 'fi-fieldset-not-contained',
                className,
            ]
                .filter(Boolean)
                .join(' '),
        },
        label != null &&
            typeof label !== 'boolean' &&
            (typeof label !== 'string' || label.trim() !== '')
            ? createElement(
                  'legend',
                  null,
                  label,
                  required
                      ? createElement(
                            'sup',
                            { className: 'fi-fieldset-label-required-mark' },
                            '*',
                        )
                      : null,
              )
            : null,
        children,
    )
})

// packages/support/resources/js/svelte/Fieldset.svelte
<script lang="ts">
    import type { Snippet } from 'svelte'
    import type { HTMLFieldsetAttributes } from 'svelte/elements'

    let {
        contained = true,
        label = null,
        labelHidden = false,
        required = false,
        class: className = '',
        children,
        ...attributes
    }: Omit<HTMLFieldsetAttributes, 'class'> & {
        contained?: boolean
        label?: string | Snippet | null
        labelHidden?: boolean
        required?: boolean
        class?: string
        children?: Snippet
    } = $props()
</script>

<fieldset
    {...attributes}
    class={[
        'fi-fieldset',
        labelHidden && 'fi-fieldset-label-hidden',
        !contained && 'fi-fieldset-not-contained',
        className,
    ]
        .filter(Boolean)
        .join(' ')}
>
    {#if typeof label === 'function' || label?.trim()}
        <legend>
            {#if typeof label === 'function'}{@render label()}{:else}{label}{/if}{#if required}<sup
                    class="fi-fieldset-label-required-mark">*</sup
                >{/if}
        </legend>
    {/if}
    {@render children?.()}
</fieldset>
